language: node_js
# nodejs版本
node_js:
    - '8'

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:

# 无其他依赖项所以执行npm test 构建就行了
script:
  - npm test

after_script:
  - NODE_ENV=test ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

# 阶段成功时执行
after_success:
  - cd ./test
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://${GIT_TOKEN}@${GH_REF}" master:${P_BRANCH}
# E: Build LifeCycle

# 阶段失败时执行
after_failure:
  - git status

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
env:
 global:
   # 我将其添加到了travis-ci的环境变量中
   #- GH_REF: github.com/imdwpeng/travis-test.git

